### ISSUE TITLE
Failed to compille 0.1.2 on Windows 7 64bit

### ISSUE THREAD

**Issue by raum-dellamorte** [mirah/mirah#242]
Windows 7 64 bit with 64 bit jdk 1.7.0_45, ant 1.8.2 from WinAnt installer, dependencies installed with jruby -S bundle install.  Not sure what else is relevant.

    >jruby -S rake gem
    ** Invoke gem (first_time)
    ** Invoke bootstrap (first_time)
    ** Invoke javalib/mirah-bootstrap.jar (first_time)
    ** Invoke javalib/mirah-newast-transitional.jar (first_time, not_needed)
    ** Invoke src/org/mirah/MirahClassLoader.java (first_time, not_needed)
    ** Invoke src/org/mirah/IsolatedResourceLoader.java (first_time, not_needed)
    ** Invoke src/org/mirah/MirahLogFormatter.mirah (first_time, not_needed)
    ** Invoke src/org/mirah/util/simple_diagnostics.mirah (first_time, not_needed)
    ** Invoke src/org/mirah/macros/builder.mirah (first_time, not_needed)
    ** Invoke src/org/mirah/macros/interfaces.mirah (first_time, not_needed)
    ** Invoke src/org/mirah/typer/assignable_type_future.mirah (first_time, not_needed)
    ** Invoke src/org/mirah/typer/assignment_future.mirah (first_time, not_needed)
    ** Invoke src/org/mirah/typer/base_type_future.mirah (first_time, not_needed)
    ** Invoke src/org/mirah/typer/block_future.mirah (first_time, not_needed)
    ** Invoke src/org/mirah/typer/block_type.mirah (first_time, not_needed)
    ** Invoke src/org/mirah/typer/call_future.mirah (first_time, not_needed)
    ** Invoke src/org/mirah/typer/closures.mirah (first_time, not_needed)
    ** Invoke src/org/mirah/typer/delegate_future.mirah (first_time, not_needed)
    ** Invoke src/org/mirah/typer/derived_future.mirah (first_time, not_needed)
    ** Invoke src/org/mirah/typer/error_type.mirah (first_time, not_needed)
    ** Invoke src/org/mirah/typer/futures.mirah (first_time, not_needed)
    ** Invoke src/org/mirah/typer/future_printer.mirah (first_time, not_needed)
    ** Invoke src/org/mirah/typer/generic_type_future.mirah (first_time, not_needed)
    ** Invoke src/org/mirah/typer/inline_code.mirah (first_time, not_needed)
    ** Invoke src/org/mirah/typer/local_future.mirah (first_time, not_needed)
    ** Invoke src/org/mirah/typer/method_future.mirah (first_time, not_needed)
    ** Invoke src/org/mirah/typer/method_type.mirah (first_time, not_needed)
    ** Invoke src/org/mirah/typer/narrowing_type_future.mirah (first_time, not_needed)
    ** Invoke src/org/mirah/typer/pick_first.mirah (first_time, not_needed)
    ** Invoke src/org/mirah/typer/scopes.mirah (first_time, not_needed)
    ** Invoke src/org/mirah/typer/simple_future.mirah (first_time, not_needed)
    ** Invoke src/org/mirah/typer/special_type.mirah (first_time, not_needed)
    ** Invoke src/org/mirah/typer/typer.mirah (first_time, not_needed)
    ** Invoke src/org/mirah/typer/types.mirah (first_time, not_needed)
    ** Invoke src/org/mirah/typer/unreachable_type.mirah (first_time, not_needed)
    ** Invoke src/org/mirah/typer/simple/list_wrapper.mirah (first_time, not_needed)
    ** Invoke src/org/mirah/typer/simple/simple_scope.mirah (first_time, not_needed)
    ** Invoke src/org/mirah/typer/simple/simple_scoper.mirah (first_time, not_needed)
    ** Invoke src/org/mirah/typer/simple/simple_type.mirah (first_time, not_needed)
    ** Invoke src/org/mirah/typer/simple/simple_types.mirah (first_time, not_needed)
    ** Invoke src/org/mirah/typer/simple/type_printer.mirah (first_time, not_needed)
    ** Invoke src/org/mirah/macros/anno/Extensions.java (first_time, not_needed)
    ** Invoke src/org/mirah/macros/anno/MacroArgs.java (first_time, not_needed)
    ** Invoke src/org/mirah/macros/anno/MacroDef.java (first_time, not_needed)
    ** Execute javalib/mirah-bootstrap.jar
    rm -rf build/bootstrap
    mkdir -p build/bootstrap
    Compiling 10 source files to D:\gdrive\projects\dev\mirah\mirah\build\bootstrap
    D:\gdrive\projects\dev\mirah\mirah\src\org\mirah\IsolatedResourceLoader.java
    D:\gdrive\projects\dev\mirah\mirah\src\org\mirah\MirahClassLoader.java
    D:\gdrive\projects\dev\mirah\mirah\src\org\mirah\jvm\compiler\Cleaned.java
    D:\gdrive\projects\dev\mirah\mirah\src\org\mirah\jvm\types\Flags.java
    D:\gdrive\projects\dev\mirah\mirah\src\org\mirah\jvm\types\MemberAccess.java
    D:\gdrive\projects\dev\mirah\mirah\src\org\mirah\jvm\types\MemberKind.java
    D:\gdrive\projects\dev\mirah\mirah\src\org\mirah\jvm\types\Modifiers.java
    D:\gdrive\projects\dev\mirah\mirah\src\org\mirah\macros\anno\Extensions.java
    D:\gdrive\projects\dev\mirah\mirah\src\org\mirah\macros\anno\MacroArgs.java
    D:\gdrive\projects\dev\mirah\mirah\src\org\mirah\macros\anno\MacroDef.java
    Note: D:\gdrive\projects\dev\mirah\mirah\src\org\mirah\MirahClassLoader.java uses unchecked or unsafe operations.
    Note: Recompile with -Xlint:unchecked for details.
    java -jar D:/gdrive/projects/dev/mirah/mirah/javalib/mirah-newast-transitional.jar compile --classpath D:/gdrive/projects/dev/mirah/mirah/javalib/mirah-parser.jar;D:/gdrive/projects/dev/mirah/mirah/build/bootstrap -d D:/gdrive/projects/dev/mirah/mirah/build/bootstrap --jvm 1.5 src/org/mirah/macros src/org/mirah/MirahLogFormatter.mirah src/org/mirah/typer src/org/mirah/util/simple_diagnostics.mirah
    Parsing...
      src/org/mirah/macros/builder.mirah
      src/org/mirah/macros/interfaces.mirah
      src/org/mirah/MirahLogFormatter.mirah
      src/org/mirah/typer/assignable_type_future.mirah
      src/org/mirah/typer/assignment_future.mirah
      src/org/mirah/typer/base_type_future.mirah
      src/org/mirah/typer/block_future.mirah
      src/org/mirah/typer/block_type.mirah
      src/org/mirah/typer/call_future.mirah
      src/org/mirah/typer/closures.mirah
      src/org/mirah/typer/delegate_future.mirah
      src/org/mirah/typer/derived_future.mirah
      src/org/mirah/typer/error_type.mirah
      src/org/mirah/typer/futures.mirah
      src/org/mirah/typer/future_printer.mirah
      src/org/mirah/typer/generic_type_future.mirah
      src/org/mirah/typer/inline_code.mirah
      src/org/mirah/typer/local_future.mirah
      src/org/mirah/typer/method_future.mirah
      src/org/mirah/typer/method_type.mirah
      src/org/mirah/typer/narrowing_type_future.mirah
      src/org/mirah/typer/pick_first.mirah
      src/org/mirah/typer/scopes.mirah
      src/org/mirah/typer/simple_future.mirah
      src/org/mirah/typer/special_type.mirah
      src/org/mirah/typer/typer.mirah
      src/org/mirah/typer/types.mirah
      src/org/mirah/typer/unreachable_type.mirah
      src/org/mirah/util/simple_diagnostics.mirah
      src/org/mirah/typer/simple/list_wrapper.mirah
      src/org/mirah/typer/simple/simple_scope.mirah
      src/org/mirah/typer/simple/simple_scoper.mirah
      src/org/mirah/typer/simple/simple_type.mirah
      src/org/mirah/typer/simple/simple_types.mirah
      src/org/mirah/typer/simple/type_printer.mirah
    Inferring types...
    src/org/mirah/macros/builder.mirah:52: undefined method `declared_instance_methods' for Type(error):Mirah::AST::TypeReference
      def initialize(objects:List)
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        @index = 0
    ^^^^^^^^^^^^^^
        @objects = objects
    ^^^^^^^^^^^^^^^^^^^^^^
      end
    ^^^^^^
    Exception in thread "main" org.jruby.exceptions.RaiseException: (NoMethodError) undefined method `declared_instance_methods' for Type(error):Mirah::AST::TypeReference
            at Mirah::JVM::MethodLookup.find_jls(file:/D:/gdrive/projects/dev/mirah/mirah/javalib/mirah-newast-transitional.jar!/mirah/jvm/method_lookup.rb:65)
            at Mirah::JVM::MethodLookup.find_method(file:/D:/gdrive/projects/dev/mirah/mirah/javalib/mirah-newast-transitional.jar!/mirah/jvm/method_lookup.rb:43)
            at Mirah::JVM::Typer.infer_signature(file:/D:/gdrive/projects/dev/mirah/mirah/javalib/mirah-newast-transitional.jar!/mirah/jvm/typer.rb:155)
            at Mirah::AST::ConstructorDefinition.infer(file:/D:/gdrive/projects/dev/mirah/mirah/javalib/mirah-newast-transitional.jar!/mirah/ast/method.rb:262)
            at Mirah::AST::ConstructorDefinition.resolve_if(file:/D:/gdrive/projects/dev/mirah/mirah/javalib/mirah-newast-transitional.jar!/mirah/ast/method.rb:292)
            at Mirah::AST::Node.resolve_if(file:/D:/gdrive/projects/dev/mirah/mirah/javalib/mirah-newast-transitional.jar!/mirah/ast.rb:247)
            at Mirah::AST::MethodDefinition.resolve_if(file:/D:/gdrive/projects/dev/mirah/mirah/javalib/mirah-newast-transitional.jar!/mirah/ast/method.rb:291)
            at Mirah::AST::MethodDefinition.infer(file:/D:/gdrive/projects/dev/mirah/mirah/javalib/mirah-newast-transitional.jar!/mirah/ast/method.rb:239)
            at Mirah::AST::ConstructorDefinition.infer(file:/D:/gdrive/projects/dev/mirah/mirah/javalib/mirah-newast-transitional.jar!/mirah/ast/method.rb:389)
            at Mirah::Typer::Simple.infer(file:/D:/gdrive/projects/dev/mirah/mirah/javalib/mirah-newast-transitional.jar!/mirah/typer/simple.rb:275)
            at Mirah::AST::Body.infer(file:/D:/gdrive/projects/dev/mirah/mirah/javalib/mirah-newast-transitional.jar!/mirah/ast/structure.rb:35)
            at org.jruby.RubyArray.each(org/jruby/RubyArray.java:1602)
            at org.jruby.RubyEnumerable.each_with_index(org/jruby/RubyEnumerable.java:910)
            at Mirah::AST::Body.infer(file:/D:/gdrive/projects/dev/mirah/mirah/javalib/mirah-newast-transitional.jar!/mirah/ast/structure.rb:33)
            at Mirah::Typer::Simple.infer(file:/D:/gdrive/projects/dev/mirah/mirah/javalib/mirah-newast-transitional.jar!/mirah/typer/simple.rb:275)
            at Mirah::AST::Body.infer(file:/D:/gdrive/projects/dev/mirah/mirah/javalib/mirah-newast-transitional.jar!/mirah/ast/structure.rb:35)
            at org.jruby.RubyArray.each(org/jruby/RubyArray.java:1602)
            at org.jruby.RubyEnumerable.each_with_index(org/jruby/RubyEnumerable.java:910)
            at Mirah::AST::Body.infer(file:/D:/gdrive/projects/dev/mirah/mirah/javalib/mirah-newast-transitional.jar!/mirah/ast/structure.rb:33)
            at Mirah::Typer::Simple.infer(file:/D:/gdrive/projects/dev/mirah/mirah/javalib/mirah-newast-transitional.jar!/mirah/typer/simple.rb:275)
            at Mirah::AST::ClassDefinition.infer(file:/D:/gdrive/projects/dev/mirah/mirah/javalib/mirah-newast-transitional.jar!/mirah/ast/class.rb:110)
            at Mirah::Typer::Simple.define_type(file:/D:/gdrive/projects/dev/mirah/mirah/javalib/mirah-newast-transitional.jar!/mirah/typer/simple.rb:93)
            at Mirah::AST::ClassDefinition.infer(file:/D:/gdrive/projects/dev/mirah/mirah/javalib/mirah-newast-transitional.jar!/mirah/ast/class.rb:108)
            at Mirah::AST::Node.resolve_if(file:/D:/gdrive/projects/dev/mirah/mirah/javalib/mirah-newast-transitional.jar!/mirah/ast.rb:247)
            at Mirah::AST::ClassDefinition.infer(file:/D:/gdrive/projects/dev/mirah/mirah/javalib/mirah-newast-transitional.jar!/mirah/ast/class.rb:104)
            at Mirah::Typer::Simple.infer(file:/D:/gdrive/projects/dev/mirah/mirah/javalib/mirah-newast-transitional.jar!/mirah/typer/simple.rb:275)
            at Mirah::AST::Body.infer(file:/D:/gdrive/projects/dev/mirah/mirah/javalib/mirah-newast-transitional.jar!/mirah/ast/structure.rb:35)
            at org.jruby.RubyArray.each(org/jruby/RubyArray.java:1602)
            at org.jruby.RubyEnumerable.each_with_index(org/jruby/RubyEnumerable.java:910)
            at Mirah::AST::Body.infer(file:/D:/gdrive/projects/dev/mirah/mirah/javalib/mirah-newast-transitional.jar!/mirah/ast/structure.rb:33)
            at Mirah::Typer::Simple.infer(file:/D:/gdrive/projects/dev/mirah/mirah/javalib/mirah-newast-transitional.jar!/mirah/typer/simple.rb:275)
            at Mirah::AST::Script.infer(file:/D:/gdrive/projects/dev/mirah/mirah/javalib/mirah-newast-transitional.jar!/mirah/ast/structure.rb:269)
            at Mirah::AST::Node.resolve_if(file:/D:/gdrive/projects/dev/mirah/mirah/javalib/mirah-newast-transitional.jar!/mirah/ast.rb:247)
            at Mirah::AST::Script.infer(file:/D:/gdrive/projects/dev/mirah/mirah/javalib/mirah-newast-transitional.jar!/mirah/ast/structure.rb:264)
            at Mirah::Typer::Simple.infer(file:/D:/gdrive/projects/dev/mirah/mirah/javalib/mirah-newast-transitional.jar!/mirah/typer/simple.rb:275)
            at Mirah::Generator.infer_asts(file:/D:/gdrive/projects/dev/mirah/mirah/javalib/mirah-newast-transitional.jar!/mirah/generator.rb:47)
            at org.jruby.RubyArray.each(org/jruby/RubyArray.java:1602)
            at Mirah::Generator.infer_asts(file:/D:/gdrive/projects/dev/mirah/mirah/javalib/mirah-newast-transitional.jar!/mirah/generator.rb:47)
            at Mirah::Generator.generate(file:/D:/gdrive/projects/dev/mirah/mirah/javalib/mirah-newast-transitional.jar!/mirah/generator.rb:35)
            at Mirah::Commands::Compile.execute(file:/D:/gdrive/projects/dev/mirah/mirah/javalib/mirah-newast-transitional.jar!/mirah/commands/compile.rb:26)
            at Mirah::Commands::Compile.execute_base(file:/D:/gdrive/projects/dev/mirah/mirah/javalib/mirah-newast-transitional.jar!/mirah/commands/base.rb:41)
            at org.jruby.RubyKernel.catch(org/jruby/RubyKernel.java:1191)
            at Mirah::Commands::Base.execute_base(file:/D:/gdrive/projects/dev/mirah/mirah/javalib/mirah-newast-transitional.jar!/mirah/commands/base.rb:38)
            at Mirah::Commands::Compile.execute(file:/D:/gdrive/projects/dev/mirah/mirah/javalib/mirah-newast-transitional.jar!/mirah/commands/compile.rb:23)
            at #<Class:0x17684731c>.compile(file:/D:/gdrive/projects/dev/mirah/mirah/javalib/mirah-newast-transitional.jar!/mirah.rb:44)
            at #<Class:0x10f8b531d>.compile(src/org/mirah/mirah_command.rb:47)
            at #<Class:0x10f8b531d>.main(src/org/mirah/mirah_command.rb:37)
    rake aborted!
    Command failed with status (1): [java -jar D:/gdrive/projects/dev/mirah/mir...]
    D:/dev/jruby/1.7.8/lib/ruby/gems/shared/gems/rake-10.1.1/lib/rake/file_utils.rb:55:in `create_shell_runner'
    org/jruby/RubyProc.java:271:in `call'
    D:/dev/jruby/1.7.8/lib/ruby/gems/shared/gems/rake-10.1.1/lib/rake/file_utils.rb:45:in `sh'
    D:/dev/jruby/1.7.8/lib/ruby/gems/shared/gems/rake-10.1.1/lib/rake/file_utils_ext.rb:41:in `sh'
    D:/gdrive/projects/dev/mirah/mirah/Rakefile:487:in `runjava'
    D:/gdrive/projects/dev/mirah/mirah/Rakefile:482:in `bootstrap_mirahc'
    org/jruby/RubyDir.java:476:in `chdir'
    D:/gdrive/projects/dev/mirah/mirah/Rakefile:481:in `bootstrap_mirahc'
    D:/gdrive/projects/dev/mirah/mirah/Rakefile:254:in `(root)'
    org/jruby/RubyProc.java:271:in `call'
    D:/dev/jruby/1.7.8/lib/ruby/gems/shared/gems/rake-10.1.1/lib/rake/task.rb:236:in `execute'
    org/jruby/RubyArray.java:1613:in `each'
    D:/dev/jruby/1.7.8/lib/ruby/gems/shared/gems/rake-10.1.1/lib/rake/task.rb:231:in `execute'
    D:/dev/jruby/1.7.8/lib/ruby/gems/shared/gems/rake-10.1.1/lib/rake/task.rb:175:in `invoke_with_call_chain'
    D:/dev/jruby/1.7.8/lib/ruby/1.9/monitor.rb:211:in `mon_synchronize'
    D:/dev/jruby/1.7.8/lib/ruby/gems/shared/gems/rake-10.1.1/lib/rake/task.rb:168:in `invoke_with_call_chain'
    D:/dev/jruby/1.7.8/lib/ruby/gems/shared/gems/rake-10.1.1/lib/rake/task.rb:197:in `invoke_prerequisites'
    org/jruby/RubyArray.java:1613:in `each'
    D:/dev/jruby/1.7.8/lib/ruby/gems/shared/gems/rake-10.1.1/lib/rake/task.rb:195:in `invoke_prerequisites'
    D:/dev/jruby/1.7.8/lib/ruby/gems/shared/gems/rake-10.1.1/lib/rake/task.rb:174:in `invoke_with_call_chain'
    D:/dev/jruby/1.7.8/lib/ruby/1.9/monitor.rb:211:in `mon_synchronize'
    D:/dev/jruby/1.7.8/lib/ruby/gems/shared/gems/rake-10.1.1/lib/rake/task.rb:168:in `invoke_with_call_chain'
    D:/dev/jruby/1.7.8/lib/ruby/gems/shared/gems/rake-10.1.1/lib/rake/task.rb:197:in `invoke_prerequisites'
    org/jruby/RubyArray.java:1613:in `each'
    D:/dev/jruby/1.7.8/lib/ruby/gems/shared/gems/rake-10.1.1/lib/rake/task.rb:195:in `invoke_prerequisites'
    D:/dev/jruby/1.7.8/lib/ruby/gems/shared/gems/rake-10.1.1/lib/rake/task.rb:174:in `invoke_with_call_chain'
    D:/dev/jruby/1.7.8/lib/ruby/1.9/monitor.rb:211:in `mon_synchronize'
    D:/dev/jruby/1.7.8/lib/ruby/gems/shared/gems/rake-10.1.1/lib/rake/task.rb:168:in `invoke_with_call_chain'
    D:/dev/jruby/1.7.8/lib/ruby/gems/shared/gems/rake-10.1.1/lib/rake/task.rb:161:in `invoke'
    D:/dev/jruby/1.7.8/lib/ruby/gems/shared/gems/rake-10.1.1/lib/rake/application.rb:149:in `invoke_task'
    D:/dev/jruby/1.7.8/lib/ruby/gems/shared/gems/rake-10.1.1/lib/rake/application.rb:106:in `top_level'
    org/jruby/RubyArray.java:1613:in `each'
    D:/dev/jruby/1.7.8/lib/ruby/gems/shared/gems/rake-10.1.1/lib/rake/application.rb:106:in `top_level'
    D:/dev/jruby/1.7.8/lib/ruby/gems/shared/gems/rake-10.1.1/lib/rake/application.rb:115:in `run_with_threads'
    D:/dev/jruby/1.7.8/lib/ruby/gems/shared/gems/rake-10.1.1/lib/rake/application.rb:100:in `top_level'
    D:/dev/jruby/1.7.8/lib/ruby/gems/shared/gems/rake-10.1.1/lib/rake/application.rb:78:in `run'
    D:/dev/jruby/1.7.8/lib/ruby/gems/shared/gems/rake-10.1.1/lib/rake/application.rb:165:in `standard_exception_handling'
    D:/dev/jruby/1.7.8/lib/ruby/gems/shared/gems/rake-10.1.1/lib/rake/application.rb:75:in `run'
    D:/dev/jruby/1.7.8/lib/ruby/gems/shared/gems/rake-10.1.1/bin/rake:33:in `(root)'
    org/jruby/RubyKernel.java:1103:in `load'
    D:/dev/jruby/1.7.8/bin/rake:23:in `(root)'
    Tasks: TOP => gem => bootstrap => javalib/mirah-bootstrap.jar

**Comment by baroquebobcat** [comment]
bootstrapping the compiler no longer requires jruby-complete!
